# Generated by Django 5.0.6 on 2026-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20),
        ),
    ]
